version: "3.6"
services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
            #      - PUID=1000
            #      - PGID=1000
      - TZ=${TZ}
    volumes:
      -./config:/config
      -~/shared_data/b1144550/files/:/galleries
        #    ports:
        #- 80:80
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=piwigo"
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /qbittorrent"
      - "traefik.frontend.rule=Host:piwigo.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
